# Generated by Django 2.1.2 on 2018-10-27 21:38

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import musicbot.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('fb_user_id', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[(musicbot.models.StateEnum('Nuevo'), 'Nuevo'), (musicbot.models.StateEnum('Empezar'), 'Empezar'), (musicbot.models.StateEnum('Buscar letras'), 'Buscar letras'), (musicbot.models.StateEnum('Ver reportes'), 'Ver reportes'), (musicbot.models.StateEnum('Nueva canción'), 'Nueva canción'), (musicbot.models.StateEnum('De favoritos'), 'De favoritos'), (musicbot.models.StateEnum('Mostrar letras'), 'Mostrar letras'), (musicbot.models.StateEnum('Guardar en favoritos'), 'Guardar en favoritos')], max_length=100)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicbot.Conversation')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=100)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicbot.Conversation')),
            ],
        ),
    ]
